### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by jzofficial66**
Adding image to the recipe.

## 🎯 Objective

Adding a picture to help people understand the dish

## 🛠️ Changes made

Just added a picture

## 👥 Who needs to review this Pull Request? 

@boncobee @wyattmdavis @baldjeff @stalerat 
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Comment by wyattmdavis** [comment]
@jzofficial66 can you add the objective, what changes were made, and who needs to review to this pull request?

**Review by wyattmdavis — APPROVED** [review]
@jzofficial66 looks great - love the addition of a photo!

**Review by dhruvkc — APPROVED** [review]
Looks good to me!

**Review by boncobee — APPROVED** [review]
Hooyah!

**Comment by wyattmdavis** [comment]
Merging with the main branch

**Pull request merged**
