### PR TITLE
dinner_update_boncobee_v1

### PR DESCRIPTION
**Pull request by boncobee**
Requesting for review from @baldjeff and @dhruvkc

## 🎯 Objective

Creating the dinner menu

## 🛠️ Changes made

Added updates in the following sections:

Recipe name
Servings:
Time to prepare:
Ingredients:
Equipment needed:
Steps for preparation:
Notes:
Codemates

## 👥 Who needs to review this Pull Request? 

Asking for review from @baldjeff @dhruvkc

### CODE REVIEW

**Review by baldjeff — COMMENTED** [review]
Hey guys, can you delete the '+' in lines 22 and 30? Otherwise looks good to me! Who's cooking?

**Comment by boncobee** [comment]
done! and resubmitted as dinner_update_boncobee_v2

**Review by dhruvkc — APPROVED** [review]
looks good to me @boncobee !

**Comment by dhruvkc** [comment]
@jzofficial66 @boncobee @wyattmdavis @baldjeff Closed out this out-of-date request to resolve conflict, we should be good to proceed with approvals on V2!

**Pull request closed without merging**
