### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by boncobee**
## 🎯 Objective

Added fried rice to the lunch menu

## 🛠️ Changes made

Made changes to ingredients section, equipment section, and directions to add what was necessary for fried rice

## 👥 Who needs to review this Pull Request? 

@jzofficial66  @baldjeff @wyattmdavis @dhruvkc

### CODE REVIEW

**Review by jzofficial66 — APPROVED** [review]
Looks great!

**Review by wyattmdavis — APPROVED** [review]
Looks good @boncobee !! I added bullets to the ingredients section so it's a bit easier to read

**Review by dhruvkc — APPROVED** [review]
Looks good to me! Good additions team!

**Comment by wyattmdavis** [comment]
Looks great! merging with main branch!

**Pull request merged**
