### PR TITLE
"Lunch proposal" V2

### PR DESCRIPTION
**Pull request by jzofficial66**
Reverts IntroToCode/RecipesCodemates8#6

### CODE REVIEW

**Comment by wyattmdavis** [comment]
@jzofficial66 can you add me as a reviewer on this pull request and any future lunch pull requests? I haven't been the reviewer on anything yet 👀 so need to be for the assignment requirements! ✅ 👍

**Review by boncobee — APPROVED** [review]

**Comment by dhruvkc** [comment]
Looks great to me!! @wyattmdavis thoughts?

**Review by dhruvkc — APPROVED** [review]
Looks good, changes approved.

**Review by wyattmdavis — CHANGES_REQUESTED** [review]
@jzofficial66 looks great! just a few issues with the headings at the top
- Can you remove "replace with recipe name"
- can you add back in "6 people" and "30 mins total"

Once those changes are made i think it will be good to go!

**Comment by jzofficial66** [comment]
> @jzofficial66 looks great! just a few issues with the headings at the top
> 
> * Can you remove "replace with recipe name"
> * can you add back in "6 people" and "30 mins total"
> 
> Once those changes are made i think it will be good to go!

Will do!

**Comment by jzofficial66** [comment]
Realized this was an accidental request to revert lunch that was already added.

**Pull request merged**
